---
- name: install python pip package
  apt: pkg=python-pip state=present

- name: install python fastools package
  pip: name=fastools
       version=0.11.1
       state=present

- name: download reference genome
  get_url:
    dest: /opt/varda/genome/genome.fa.gz
    url: "{{ varda_genome }}"
    sha256sum: "{{ varda_genome_sha256sum }}"
  sudo_user: varda

- name: decompress reference genome
  shell: gunzip -c /opt/varda/genome/genome.fa.gz | fastools sanitise - /opt/varda/genome/genome.fa creates=/opt/varda/genome/genome.fa
  sudo_user: varda
  notify:
    - reload varda api
    - reload varda celery
