---
- name: install varda requirements
  pip: requirements=/opt/varda/src/varda/requirements.txt
       virtualenv=/opt/varda/versions/{{ varda_current }}/virtualenv
       state=present
  become_user: varda

- name: install varda
  pip: name=/opt/varda/src/varda
       virtualenv=/opt/varda/versions/{{ varda_current }}/virtualenv
       state=latest
  become_user: varda

- name: run unit tests
  command: /opt/varda/versions/{{ varda_current }}/virtualenv/bin/nosetests chdir=/opt/varda/src/varda
  changed_when: false
  become_user: varda
  when: varda_unit_tests

- name: setup varda database
  shell: "VARDA_SETTINGS=/opt/varda/versions/{{ varda_current }}/conf/settings.py /opt/varda/versions/{{ varda_current }}/virtualenv/bin/varda setup --admin-password '{{ varda_admin_password }}' --alembic-config /opt/varda/src/varda/alembic.ini"
  become_user: varda

- name: migrate varda database
  shell: "VARDA_SETTINGS=/opt/varda/versions/{{ varda_current }}/conf/settings.py /opt/varda/versions/{{ varda_current }}/virtualenv/bin/alembic -c /opt/varda/src/varda/alembic.ini upgrade head"
  become_user: varda
