# -*- mode: ruby -*-
# vi: set ft=ruby :
IP = ENV['VARDA_IP'] || '192.168.111.224'
PORT_FORWARD_SSH = ENV['VARDA_PORT_FORWARD_SSH'] || '2524'
PORT_FORWARD_HTTP = ENV['VARDA_PORT_FORWARD_HTTP'] || '8090'
PORT_FORWARD_HTTPS = ENV['VARDA_PORT_FORWARD_HTTPS'] || '8091'
MEMORY = ENV['VARDA_MEMORY'] || '1024'
CORES = ENV['VARDA_CORES'] || '1'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Debian 8 (Jessie) base image.
  config.vm.box = "debian/jessie64"

  # We don't need a shared folder.
  config.vm.synced_folder ".", "/vagrant", :disabled => true

  # Set VM hostname.
  config.vm.hostname = "varda-vagrant"

  # Port forwards for HTTP and HTTPS.
  config.vm.network :forwarded_port, guest: 80, host: PORT_FORWARD_HTTP.to_i
  config.vm.network :forwarded_port, guest: 443, host: PORT_FORWARD_HTTPS.to_i

  # Also override the default SSH port forward.
  config.vm.network :forwarded_port, guest: 22, host: PORT_FORWARD_SSH.to_i, auto_correct: false, id: "ssh"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: IP

  # Provision using our Ansible playbook.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory"
    ansible.host_key_checking = false
  end

  config.ssh.insert_key = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    #vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", MEMORY.to_i]
    vb.customize ["modifyvm", :id, "--cpus", CORES.to_i]
  end

  # View the documentation for the provider you're using for more
  # information on available options.
end
